### ISSUE TITLE
Migrating to exisitng coinbase wallet

### ISSUE THREAD

**Issue by shotcollin** [breadwallet/brd-mobile#25]
The available instructions for migration don't seem to cover cases where the user already *has* coinbase wallet. There is no option when you open coinbase wallet to tap "I already have a wallet" (as per the instructions) if one already literally has a coinbase wallet. I don't see anything within coinbase wallet's options, settings, etc, to add a new wallet/import a new passphrase to an existing wallet. There is nothing on coinbase's available support regarding BRD wallet imports.

I recently restored BRD wallet to my device because I need to export the transaction history for tax purposes. I don't actually even care about importing the brd wallet to coinbase, all I want is tx history, but when I export the csv file (great feature, btw, if it worked) using brd wallet, the file is empty. I definitely transacted many times with brd when using the wallet, however. 

Please advise how to either import the wallet to an existing coinbase wallet or properly access full transaction history.

**Comment by shivangigandhi** [comment]
Hi @shotcollin, 

At this time Coinbase wallet does not support recovering multiple private keys on 1 account. 

A few things you could try:
1. Create a new Coinbase Wallet Account to get your tx history from there. 

2. The Android version of the feature has been broken for some time, and as the company has shut down, we'll not be able to fix it. If your issue is on Android, please try on iOS as that *should* still be working. 

3. I think that Electrum on desktop supports our derivation path.  So you may want to try that and see if that wallet has what you need. 

Hope that helps! Thanks!

**Comment by shotcollin** [comment]
Hi @shivangigandhi,

Thanks for the info. I wasn't able to create a new Coinbase wallet account, at least by uninstalling and re-installing the app on iOS, including on other iOS devices, because it seems the account info isn't removed upon uninstall and of course Apple has to share that info across all devices...

I'd like to try Electrum since I've been successful restoring other wallets using it. I see there have been some other issues about derivation path recently but am not sure I found the right one. Can you confirm what derivation path I should use to try the Electrum route?

Thanks!

**Comment by shotcollin** [comment]
I was able to import bread wallet using a different iOS device that didn't already have coinbase wallet installed.
